//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNet基础.EntityFramework.模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_Info
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public bool IsSuccess { get; set; }
        public bool IsShelves { get; set; }
        public string LogName { get; set; }
        public string ComTypeName { get; set; }
        public string ComTypeTableName { get; set; }
        public string Title { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string txt { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> FrontImageID { get; set; }
        public Nullable<int> BondID { get; set; }
        public int ReadCounts { get; set; }
    }
}
