//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNet基础.EntityFramework.模型
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_User
    {
        public int id { get; set; }
        public string Emal { get; set; }
        public string LogName { get; set; }
        public string UserName { get; set; }
        public string LogPwd { get; set; }
        public string FuPwd { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Head { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IdentityCode { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Borough { get; set; }
        public string GzProvince { get; set; }
        public string GzCity { get; set; }
        public string GzBorough { get; set; }
        public string Address { get; set; }
        public bool IsDefAddress { get; set; }
        public string Question1 { get; set; }
        public string Question1daan { get; set; }
        public string Question2 { get; set; }
        public string Question2daan { get; set; }
        public string Question3 { get; set; }
        public string Question3daan { get; set; }
        public string SendModes { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UserType { get; set; }
        public bool IsChangeAcc { get; set; }
        public bool IsLocked { get; set; }
        public bool IsMobileVal { get; set; }
        public int IsIdentityCodeVal { get; set; }
        public int IsBandBindVal { get; set; }
    }
}
