//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNet基础.EntityFramework.模型
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuNiEntities : DbContext
    {
        public HuNiEntities()
            : base("name=HuNiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Base_Area> Base_Area { get; set; }
        public DbSet<Base_keyWord> Base_keyWord { get; set; }
        public DbSet<Bus_Info> Bus_Info { get; set; }
        public DbSet<Bus_User> Bus_User { get; set; }
    }
}
